displayName=Don't Telegrab NPCs
author=ldavid432
description=Disables casting telegrab on NPCs
tags=telekinetic,grab,npc,monster,no,telegrab,block
plugins=com.github.ldavid432.DontTelegrabPlugin
build=standard
version=1.0.5
